### ISSUE TITLE
I'm upset because this library dost not support API8+

### ISSUE THREAD

**Issue by BCsl** [birajpatel/GridListViewAdapters#1]

**Comment by birajpatel** [comment]
Hi,
I think you are making some mistake the library is supported all the way from API4 to API21
In fact, the library-demo-samples itself is written on API-11. please let me know how you are not able to use it above 8+

**Comment by birajpatel** [comment]
Hey, since this is an invalid issue I am closing it, write to me personally If you still face the issue in integrating it.
biraj.d.patel@gmail.com

**Comment by BCsl** [comment]
i am  sorry about that .it s my mistake ,i had misunderstood it.
